language: python
python:
  - "3.6"
install:
  # install deps
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls
script:
  - python3 manage.py migrate
  - coverage run --source='.' ./manage.py test
  # Code coverage
  - coverage report
after_scripts:
  - coveralls
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: favorite-things-back
  on:
    repo: matthewacha/favorite-things
    branch: master
addons:
  postgresql: "9.6"
