sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 3.0
before_install:
  # install heroku cli
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker login --username $HEROKU_USERNAME --password $HEROKU_API_KEY registry.heroku.com
install:
  # install deps
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls
script:
  - python3 manage.py migrate
  - coverage run --source='.' ./manage.py test
  # Code coverage
  - coverage report
  # build docker images
  - docker image build -t $HEROKU_APP_NAME .
  - docker images
  # - docker-compose --version
  # - docker-compose build
  - docker images ls
  - docker tag $HEROKU_APP_NAME $DOCKER_USERNAME/$HEROKU_APP_NAME
  - docker tag $HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push $DOCKER_USERNAME/$HEROKU_APP_NAME:latest
  - heroku stack:set container -a $HEROKU_APP_NAME
after_scripts:
  - coveralls
deploy:
  provider: script
  script:
    # run container in heroku
    heroku container:release web -a $HEROKU_APP_NAME
  branch: ft-custom-user-views
addons:
  postgresql: "9.6"