# Generated by Django 2.0.3 on 2019-06-22 20:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0005_auto_20190622_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
