# Generated by Django 2.0.3 on 2019-06-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0007_auto_20190623_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
