# Generated by Django 2.0.3 on 2019-06-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0010_auto_20190624_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.CustomUser'),
        ),
    ]
