# Generated by Django 2.0.3 on 2019-06-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0016_auto_20190627_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
