# Generated by Django 2.0.3 on 2019-06-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0004_auto_20190622_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='category',
            field=models.CharField(choices=[('pe', 'person'), ('pl', 'place'), ('fo', 'food')], max_length=255),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
