# Generated by Django 2.0.3 on 2019-06-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0006_favorite_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
